# docker-compose.yml
version: '3.8'

services:
  interview-radar:
    build: .
    container_name: interview-radar
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./logs:/app/logs
    restart: always