spring:
    datasource:
        url: jdbc:mysql://localhost:3306/interview_radar?useSSL=false&serverTimezone=UTC
        username: root
        password: abc123

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true

llm:
    provider: deepseek

openai:
    api-key: your_openai_key
    model: gpt-4o

aliyun:
    api-key: sk-c8537643758b4d8da98f06a99dc603d9
    base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
    model:    qwen-plus

deepseek:
    api-key: sk-45d3870db5ee4d2b8d4c9ade425dbadd
    base-url: https://api.deepseek.com/v1
    model: deepseek-reasoner

crawler:
    delay-ms: 5000

classification:
    batch-size: 10

threadpool:
    core-size: 5
    max-size: 10
    queue-capacity: 50

concurrency:
    extract-tasks: 20    # 提取阶段最大并发
    classify-tasks: 10   # 分类阶段最大并发

