spring:
    datasource:
        url: jdbc:mysql://115.190.83.184:3306/interview_radar?useSSL=false&serverTimezone=Asia/Shanghai
        username: admin
        password: Sj.4330450
        hikari:
            maximum-pool-size: 300     # 连接池最大连接数
            minimum-idle: 10          # 最小空闲连接
            idle-timeout: 30000       # 空闲连接最大存活时间
            connection-timeout: 300000 # 获取连接的最大等待时间

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: false

langchain4j:
    open-ai:
        chat-model:
            timeout: 600s
#           deepseek
#            api-key: 
#            base-url: https://api.deepseek.com/v1
#            model-name: deepseek-reasoner

#           aliyun
            api-key: 
            base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
            model-name: qwen-plus


aliyun:
    embedding:
        api-key: 
        base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
        model: text-embedding-v4
        dimension: 1024

crawler:
    delay-ms: 5000

classification:
    batch-size: 5

threadpool:
    core-size: 5
    max-size: 5
    queue-capacity: 10000


milvus:
    host: 115.190.83.184
    port: 19530
    embedding-dim: 1024

